### PR TITLE
Merge Support Page Additions Into Main CSS Repository For Publishing

### PR DESCRIPTION
**Pull request by ben-marshall**
I've gone and filled out the support page of the CSS website with content. The "we're working with the department" message is still there to reflect the fact that CSS is waiting for advice from them.

It is organised into three headings: who is the page for, what problems people might have, and what services are available to students. They try to be relevant to CS students, but I aimed to get as much information on the page as possible.

On a technical note - the list of support services would be much better administered as a YAML dynamic thing like the jobs listing. I didn't trust myself to do that though, so I just wrote the content for the sake of getting it out there and available for people to use. Also, I hope I added the additional style rules in the right place? Also also, I have done nothing to the main branch, so after the merge it would still need publishing.

Keen to hear what people think! :-)

### CODE REVIEW

**Comment by JulianLaval** [comment]
Thanks for the PR; content looks good to me!

Give me a day or so to bring the styling a tad more inline with the rest and add you to the contributors.

Cheers!

**Comment by ben-marshall** [comment]
No problem, glad I can help!

Yeah I definitely went for content above style haha, thanks for clearing it up!

**Comment by ben-marshall** [comment]
Has there been any movement on this? I know Alexis is working with the department, but it'd be nice to have something up people can use. Even if it is ugly!

**Comment by JulianLaval** [comment]
The support page was put on hold for a bit as we were hoping to get content from the department. We recently decided to proceed with this, though, so I'll merge it today!

**Comment by JulianLaval** [comment]
Merged and integrated!

**Pull request closed without merging**
